/*
* generated by Xtext
*/
package org.kermeta.language.sample.cellularautomata.rules.cs.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.kermeta.language.sample.cellularautomata.rules.cs.services.RuleGrammarAccess;

public class RuleParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RuleGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.kermeta.language.sample.cellularautomata.rules.cs.parser.antlr.internal.InternalRuleParser createParser(XtextTokenStream stream) {
		return new org.kermeta.language.sample.cellularautomata.rules.cs.parser.antlr.internal.InternalRuleParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CellularAutomata";
	}
	
	public RuleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RuleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
