/*
 * generated by Xtext
 */
package org.kermeta.language.sample.cellularautomata.rules.cs;

import org.eclipse.xtext.linking.ILinker;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RuleRuntimeModule extends org.kermeta.language.sample.cellularautomata.rules.cs.AbstractRuleRuntimeModule {
	@Override
	public Class<? extends ILinker> bindILinker() {
		return CARuleLinker.class;
	}
}
